version: '3.3'
services:
  mysqldb:
    container_name: MYSQLDB
    image: mysql:latest
    restart: always
    environment:
       MYSQL_DATABASE: babydocs
       MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /Users/aseshres/Desktop/db:/var/lib/mysql
volumes:
  db-babydocs:
